In [1]:
import pandas as pd 
import numpy as np 

In [2]:
df = pd.read_csv("Datasets/Titanic-Dataset.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [3]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [4]:
df2 = df.fillna(df.mean(numeric_only=True))

In [5]:
df2 = df.fillna(df.mode())
df2['Age'] = df['Age'].fillna(df['Age'].median())
df2.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare    Cabin Embarked  
0      0         A/5 21171   7.2500  B96 B98        S  
1      0          PC 17599  71.2833      C85        C  
2      0  STON/O2. 3101282   7.9250       G6        S  
3      0            113803  53.1000     C123        S  
4      0            373450   8.0500      NaN        S

In [6]:
# As cabin is not useful we can drop it 
df2.drop('Cabin',axis=1,inplace=True)
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(4)
memory usage: 76.7+ KB


In [7]:
df2['Embarked'] = df2['Embarked'].fillna(df2['Embarked'].mode()[0])
df2.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [8]:
# Encode categorical variables 
# one hot encoding 

dummies = pd.get_dummies(df2[['Embarked', 'Sex']] , dtype=int)

# concatenate with original dataset
df_merged = pd.concat([df2, dummies], axis=1)
df_merged.drop(['Name', 'Ticket','Sex'], axis=1, inplace=True)

In [9]:
df_final = df_merged.drop(['Embarked'], axis=1)
# df_final.info()
df_final.tail()


PassengerId  Survived  Pclass   Age  SibSp  Parch   Fare  Embarked_C  \
886          887         0       2  27.0      0      0  13.00           0   
887          888         1       1  19.0      0      0  30.00           0   
888          889         0       3  28.0      1      2  23.45           0   
889          890         1       1  26.0      0      0  30.00           1   
890          891         0       3  32.0      0      0   7.75           0   

     Embarked_Q  Embarked_S  Sex_female  Sex_male  
886           0           1           0         1  
887           0           1           1         0  
888           0           1           1         0  
889           0           0           0         1  
890           1           0           0         1

#### Feature Scaling

In [10]:
df_final.tail()

PassengerId  Survived  Pclass   Age  SibSp  Parch   Fare  Embarked_C  \
886          887         0       2  27.0      0      0  13.00           0   
887          888         1       1  19.0      0      0  30.00           0   
888          889         0       3  28.0      1      2  23.45           0   
889          890         1       1  26.0      0      0  30.00           1   
890          891         0       3  32.0      0      0   7.75           0   

     Embarked_Q  Embarked_S  Sex_female  Sex_male  
886           0           1           0         1  
887           0           1           1         0  
888           0           1           1         0  
889           0           0           0         1  
890           1           0           0         1

In [31]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

X = df_final.drop('Survived', axis=1)
Y = df_final['Survived']

scaler = StandardScaler()
x_scaled = scaler.fit_transform(x)

In [57]:
x_train, x_test, y_train, y_test = train_test_split(x_scaled, Y , test_size=0.2, random_state=51)

#### MODEL TRAINING 

In [72]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression()
lr.fit(x_train, y_train)
y_pred_lr = lr.predict(x_test)

result = np.round(y_pred_lr) == np.array(y_test)

print("RATIO OF CORRECTNESS: " + str(result.sum()) + " / " +  str(result.shape[0]))

RATIO OF CORRECTNESS: 139 / 179


In [73]:
from sklearn.linear_model import LogisticRegression

LogReg = LogisticRegression()

LogReg.fit(x_train, y_train)

y_pred_logReg = LogReg.predict(x_test)

In [75]:
# Decision Tree

from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import DecisionTreeRegressor

dtree_class = DecisionTreeClassifier()
dtree_class.fit(x_train, y_train)
dt_cls_pred = dtree_class.predict(x_test)

dtree_reg = DecisionTreeRegressor()
dtree_reg.fit(x_train, y_train)
dt_reg_pred = dtree_reg.predict(x_test)


In [88]:
#knn

from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=6)
knn.fit(x_train, y_train)
y_pred_knn = knn.predict(x_test)

In [89]:
from sklearn.metrics import accuracy_score, precision_score, f1_score, confusion_matrix, recall_score

def evaluateModel(name, y_pred, y_test):
    acc = accuracy_score(y_pred, y_test)
    recall = recall_score(y_pred, y_test)
    prec = precision_score(y_pred, y_test)
    f1 = f1_score(y_pred, y_test)
    cm = confusion_matrix(y_pred, y_test)

    print("\n" + name)
    print("accuracy : ", acc)
    print("recall : ", recall)
    print("precision : ", prec)
    print("f1 score : ", f1)
    print("confusion matrix : \n", cm)
    return 

In [92]:
# model_names = {"Linear Regression", "Logistic Regression", "Decision Tree", "knn"}
# evaluateModel("Linear Regression" , y_pred_lr, y_test)
evaluateModel("Decision Tree L" , dt_cls_pred, y_test)
evaluateModel("Decision tree R" , dt_reg_pred, y_test)


Decision Tree L
accuracy :  0.7821229050279329
recall :  0.7424242424242424
precision :  0.6901408450704225
f1 score :  0.7153284671532847
confusion matrix : 
 [[91 22]
 [17 49]]

Decision tree R
accuracy :  0.776536312849162
recall :  0.7313432835820896
precision :  0.6901408450704225
f1 score :  0.7101449275362319
confusion matrix : 
 [[90 22]
 [18 49]]


In [94]:
evaluateModel("Logistic Regression" , y_pred_logReg, y_test)
evaluateModel("KNN : " , y_pred_knn, y_test)


Logistic Regression
accuracy :  0.776536312849162
recall :  0.7719298245614035
precision :  0.6197183098591549
f1 score :  0.6875
confusion matrix : 
 [[95 27]
 [13 44]]

KNN : 
accuracy :  0.776536312849162
recall :  0.803921568627451
precision :  0.5774647887323944
f1 score :  0.6721311475409836
confusion matrix : 
 [[98 30]
 [10 41]]
