### 5/3/25 -> INTRO TO NUMPY

In [35]:
import numpy as np

In [36]:
arr = np.array([1,2,3]) #1D
print(arr)

[1 2 3]


In [37]:
arr2 = np.array([[1,2,3],[4,5,6]])  #2D
print(arr2)

[[1 2 3]
 [4 5 6]]


In [38]:
arr3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])    # 3d
print(arr3)
print(arr3.shape)
print(arr3.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
(1, 3, 3)
3


In [39]:
print(arr.ndim)
print(arr.shape)

print(arr2.ndim)
print(arr2.shape)

print(arr3.ndim)
print(arr3.shape)

1
(3,)
2
(2, 3)
3
(1, 3, 3)


In [40]:
# To Find No. of elements
print(arr.size)
print(arr2.size)
print(arr3.size)

3
6
9


In [41]:
print(arr3.dtype)   # datatype

int64


In [42]:
print(arr)
print(arr.dtype)
print(arr.itemsize) # No. of bytes required by one element (64bits means 8 bytes)

[1 2 3]
int64
8


In [43]:
arr5 = np.array([[1,2],[3,4]], dtype='float')

print(arr5)
print(arr5.dtype)

arr6 = np.zeros((2,3))      # array with 2x3 elements initialised with 0's
print("\narr6\n",arr6)

arr7 = np.ones((2,4))       # array with 2x4 elements initialised with 1's
print("\narr7\n",arr7)

[[1. 2.]
 [3. 4.]]
float64

arr6
 [[0. 0. 0.]
 [0. 0. 0.]]

arr7
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [44]:
arr8 = np.arange(-100,100,20) # start,stop+1,skipValue

print("ARRAY8: \n", arr8)
print("\nSLICED ARRAY8: ",arr8[2:7]) # upto 7-1
print("\nREVERSED ARRAY8: ",arr8[::-1])

ARRAY8: 
 [-100  -80  -60  -40  -20    0   20   40   60   80]

SLICED ARRAY8:  [-60 -40 -20   0  20]

REVERSED ARRAY8:  [  80   60   40   20    0  -20  -40  -60  -80 -100]


In [45]:
marks = np.array([[76,55,45],
                  [65,78,87],
                  [87,75,54],
                  [54,53,67]])
print("marks:\n",marks)
print("\nAt [3,1] :\n", marks[3,1])
print("\nColumn:\n",marks[:4,:2])
print("\nmarks[1:3,1:3] :\n",marks[1:3,1:3])
print("\nmarks[2,:] :\n",marks[2,:])

marks:
 [[76 55 45]
 [65 78 87]
 [87 75 54]
 [54 53 67]]

At [3,1] :
 53

Column:
 [[76 55]
 [65 78]
 [87 75]
 [54 53]]

marks[1:3,1:3] :
 [[78 87]
 [75 54]]

marks[2,:] :
 [87 75 54]


In [46]:
arr_1 = np.array([[3,6],[4,2]])
arr_2 = np.array([[10,20],[11,12]])

In [47]:
# addition
print("Operation addition:\n",arr_1+arr_2)
# substraction
print("Operation substraction:\n",arr_1-arr_2)
# multiplication
print("Operation multiplication:\n",arr_1*arr_2)
# division
print("Operation division:\n",arr_1/arr_2)
# matrix multiplication
print("Operation matrix multiplication:\n",arr_1 @ arr_2)
# expo
print("expo:\n",arr_1**arr_2)

Operation addition:
 [[13 26]
 [15 14]]
Operation substraction:
 [[ -7 -14]
 [ -7 -10]]
Operation multiplication:
 [[ 30 120]
 [ 44  24]]
Operation division:
 [[0.3        0.3       ]
 [0.36363636 0.16666667]]
Operation matrix multiplication:
 [[ 96 132]
 [ 62 104]]
expo:
 [[           59049 3656158440062976]
 [         4194304             4096]]


In [48]:
newMarks = marks.transpose()
transpMarks = marks.T
print("Original Matrix:\n",marks)
print("\nTransposed Matrix with arr.transpose :\n",newMarks)
print("\nTranspose with arr.T :\n", transpMarks)

Original Matrix:
 [[76 55 45]
 [65 78 87]
 [87 75 54]
 [54 53 67]]

Transposed Matrix with arr.transpose :
 [[76 65 87 54]
 [55 78 75 53]
 [45 87 54 67]]

Transpose with arr.T :
 [[76 65 87 54]
 [55 78 75 53]
 [45 87 54 67]]


### Concept of axes
```sh
            ^
            |       *axis 2
            |     *
            |   *
            | *
<-----------|-------------> axis 1
           *|
         *  |
       *    |
     *      |
   *        |
            axis 0
```


In [49]:
print("Sorted marks array row-wise: \n", np.sort(marks))

Sorted marks array row-wise: 
 [[45 55 76]
 [65 78 87]
 [54 75 87]
 [53 54 67]]


In [50]:
print("Sorted marks array column-wise: \n", np.sort(marks,axis=0))

Sorted marks array column-wise: 
 [[54 53 45]
 [65 55 54]
 [76 75 67]
 [87 78 87]]


In [51]:
print("\n",arr_1)
print("\n",arr_2)
print("\nrow-wise:\n",np.concat([arr_1,arr_2]))         # axis 0 means row (default)
print("\ncol-wise:\n",np.concat((arr_1,arr_2),axis=1))  # axis = 1 means column


 [[3 6]
 [4 2]]

 [[10 20]
 [11 12]]

row-wise:
 [[ 3  6]
 [ 4  2]
 [10 20]
 [11 12]]

col-wise:
 [[ 3  6 10 20]
 [ 4  2 11 12]]


### use np.full() to create a constant matrix:

In [52]:
matrix = np.full((3, 3), 7)     # 3x3 matrix with all values as 7
matrix

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])