In [3]:
import numpy as np
import pandas as pd

In [4]:
numpyArray = np.array([1,2,3])

In [5]:
dataFrame1 = pd.DataFrame(numpyArray)
dataFrame1

0
0  1
1  2
2  3

In [6]:
numpyArray = np.array([1,2,3])
arr2 = np.array([3,2,1])
arr3 = np.array([4,5,6])

dataFrame2 = pd.DataFrame([numpyArray, arr2])

print("numpyArray:\n", numpyArray)
print("arr2\n" , arr2)
print("arr3\n",arr3)
print("\ndf:\n",dataFrame2)

numpyArray:
 [1 2 3]
arr2
 [3 2 1]
arr3
 [4 5 6]

df:
    0  1  2
0  1  2  3
1  3  2  1


In [7]:
uf = pd.DataFrame((numpyArray, arr2, arr3),index=["str1","str2","str3"])
uf

0  1  2
str1  1  2  3
str2  3  2  1
str3  4  5  6

In [8]:
listOfDicts = [{"a" : 1,"b" : 2},{"c" : 3,"d" : 4},{"e" : 5, "f" : 6}]
lofdf = pd.DataFrame(listOfDicts)
lofdf

# Each dictionary becomes a row in the DataFrame.
# Keys become the column names.
# If a key is missing in a row (dictionary), it's shown as NaN.

a    b    c    d    e    f
0  1.0  2.0  NaN  NaN  NaN  NaN
1  NaN  NaN  3.0  4.0  NaN  NaN
2  NaN  NaN  NaN  NaN  5.0  6.0

In [27]:
dictOfList = {"one" : [1,2,3,4,5], "two" : [6,7,8,9,10]} # Arrays should be of same length.
dOL_dataframe = pd.DataFrame(dictOfList)
print(dOL_dataframe)

   one  two
0    1    6
1    2    7
2    3    8
3    4    9
4    5   10


In [28]:
stateArray = {
    "State" : ["Bihar","WB"],
    "Area" : [12000,21000],
    "Population" : [123214,3241324]
}

pd.DataFrame(stateArray,index=["state1","state2"])

State   Area  Population
state1  Bihar  12000      123214
state2     WB  21000     3241324

In [11]:
stateArray1 = {"state" : ["Bihar","WB"], "Area" : [12321,21312],"population" : [123214,3241324]}
dfa = pd.DataFrame(stateArray1,index=["state1","state2"], columns=["state","Area","ppln"])
dfa

state   Area ppln
state1  Bihar  12321  NaN
state2     WB  21312  NaN

In [12]:
s1 = pd.Series([10,20,30], index=["a","b","c"])
s2 = pd.Series([30,40,50], index=["d","a","b"])
s3 = pd.Series([60,70,90], index=["a","d","f"])
dfa3 = pd.DataFrame([s1,s2,s3])
dfa4 = pd.DataFrame([s1,s2,s3]).fillna("--")
print(dfa3)
print(dfa4)


      a     b     c     d     f
0  10.0  20.0  30.0   NaN   NaN
1  40.0  50.0   NaN  30.0   NaN
2  60.0   NaN   NaN  70.0  90.0
      a     b     c     d     f
0  10.0  20.0  30.0    --    --
1  40.0  50.0    --  30.0    --
2  60.0    --    --  70.0  90.0


In [33]:
# dict of series
dfa44 = {
    "Luffy" : pd.Series([69,31,70],index=["Maths","Physics","Biology"]),
    "Nami" : pd.Series([64,33,20],index=["Maths","Physics","Biology"]),
    "Sanji" : pd.Series([29,31,69],index=["Maths","Physics","Biology"]),
    "Zoro" : pd.Series([69,41,80],index=["Maths","Physics","Biology"]),
}

some_df2 = pd.DataFrame(dfa44)
print(some_df2)

# method 2
some_df = pd.DataFrame({
    "Luffy": [69, 31, 70],
    "Nami": [64, 33, 20],
    "Sanji": [29, 31, 69],
    "Zoro": [69, 41, 80]
}, index=["Maths", "Physics", "Biology"])


print(some_df)


         Luffy  Nami  Sanji  Zoro
Maths       69    64     29    69
Physics     31    33     31    41
Biology     70    20     69    80
         Luffy  Nami  Sanji  Zoro
Maths       69    64     29    69
Physics     31    33     31    41
Biology     70    20     69    80


In [14]:
dfa44["Zoro"] = [69,34,90]
pd.DataFrame(dfa44)

Luffy  Nami  Sanji  Zoro
Maths       69    64     29    69
Physics     31    33     31    34
Biology     70    20     69    90

In [ ]:
some_df.loc["Science"] = [99,87,32,12]      # if exist then updates, else add a new row
# pd.DataFrame(dfa44)
some_df

Luffy  Nami  Sanji  Zoro
Maths       69    64     29    69
Physics     31    33     31    41
Biology     70    20     69    80
Science     99    87     32    12

In [16]:
some_df.drop("Science") # deletes row

Luffy  Nami  Sanji  Zoro
Maths       69    64     29    69
Physics     31    33     31    41
Biology     70    20     69    80

In [17]:
some_df.drop("Nami",axis=1) #deletes column

Luffy  Sanji  Zoro
Maths       69     29    69
Physics     31     31    41
Biology     70     69    80
Science     99     32    12

In [18]:
some_df.drop(["Zoro","Sanji"], axis=1)

Luffy  Nami
Maths       69    64
Physics     31    33
Biology     70    20
Science     99    87

In [36]:
# Changes column name
some_df.rename({"Luffy":"Monkey D Luffy","Nami" : "Nami Burglar"},axis="columns")

Monkey D Luffy  Nami Burglar  Sanji  Zoro
Maths                69            64     29    69
Physics              31            33     31    41
Biology              70            20     69    80
Science              99            87     32    12

In [20]:
some_df.loc[:"Biology"]     # same as some_df.loc["Maths":"Biology"]

Luffy  Nami  Sanji  Zoro
Maths       69    64     29    69
Physics     31    33     31    41
Biology     70    20     69    80

In [21]:
some_df.loc["Maths"] > 50       # check rows greater than 50

Luffy     True
Nami      True
Sanji    False
Zoro      True
Name: Maths, dtype: bool

In [22]:
some_df.loc["Maths":"Physics","Luffy"]

Maths      69
Physics    31
Name: Luffy, dtype: int64

In [23]:
some_df.loc[:"Physics","Luffy":]    # Two columns and One row
some_df.loc["Physics":,:"Zoro"]    # 3 columns and One row

Luffy  Nami  Sanji  Zoro
Physics     31    33     31    41
Biology     70    20     69    80
Science     99    87     32    12

In [24]:
some_df.loc[[True, False,True,False]]

Luffy  Nami  Sanji  Zoro
Maths       69    64     29    69
Biology     70    20     69    80

# Merge, joining

In [25]:
df8 = pd.DataFrame([[1,2,3],[4,5],[6]],columns=list("ace"),index=list("RSP"))
# df9 = pd.DataFrame([[1,2],[30],[63,70]],columns=list("ace"),index=list("RSP"))
df8

a    c    e
R  1  2.0  3.0
S  4  5.0  NaN
P  6  NaN  NaN